OAuth2\ServerBundle\Entity\JwtBearer:
    type: entity
    table: oauth_jwt_bearer
    id:
        jti:
            type:       string
            length:     40
    fields:
        jwt:
            type:       string
            length:     655535
        notBefore:
            type:       datetime
        issuedAt:
            type:       datetime
        expires:
            type:       datetime
        audience:
            type:       string
            length:     1024
        scope:
            type:       string
            length:     50
            nullable:   true
    manyToOne:
        client:
            targetEntity: OAuth2\ServerBundle\Entity\Client
            joinColumn:
                name: client_id
                referencedColumnName: client_id
                onDelete: CASCADE
                onUpdate: CASCADE
    lifecycleCallbacks: {  }
